pull_request_rules:
  - name: merge automated metals update PRs on CI success
    conditions:
      - author=harryprayiv
      - title=Update Metals to latest snapshot
      - check-success~=build
    actions:
      merge:
        method: merge
