{
 "title": "cardano-node (stakepool overview)",
 "description": "k8s-oriented cardano-node dashboard for metrics and logs built with 💜 by La RepsistancE: https://twitter.com/repsistance",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "type",
    "query": "label_values(mixin_pod_workload{namespace=~\"$namespace\", workload=~\".+\"}, workload_type)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "cardano-node general metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cardano-node/uptime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_upTime_ns{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/epoch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_epoch_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/block-height",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/slot-height",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/connected-peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/slot-in-epoch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotInEpoch_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/chain-density",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_density_real{namespace=~\"$namespace\", pod=~\"$pod\"} * 100",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/mempool-bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/block-sync-speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_ChainDB_metrics_blockNum_int{namespace=~\"$namespace\", pod=~\"$pod\"}[150s])*60",
     "legendFormat": "{{namespace}}-{{pod}}"
    },
    {
     "expr": "rate(cardano_node_metrics_ChainDB_blockNum_int{namespace=~\"$namespace\", pod=~\"$pod\"}[150s])*60",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/slot-length (?)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(cardano_node_metrics_Forge_forge_about_to_lead_int{namespace=~\"$namespace\", pod=~\"$pod\"}[710s])",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/txs-processed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/txs-in-mempool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  { "title": "cardano-node leader metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "cardano-node/pool-performance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int{namespace=~\"$namespace\", pod=~\"$pod\"} / cardano_node_metrics_Forge_node_is_leader_int{namespace=~\"$namespace\", pod=~\"$pod\"} * 100",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/blocks-assigned",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/forged-blocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/adopted-blocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_adopted_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/forge-about-to-lead",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forge_about_to_lead_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/forged-but-invalid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_invalid_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/could-not-forge",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_could_not_forge_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/not-adopted-blocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_didnt_adopt_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  { "title": "Resource metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Usage (cores)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} * 100\n",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "PVC free disk space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Misc metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit Bandwidth",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__interval])\n",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    },
    {
     "title": "Time Synchronization",
     "type": "graph",
     "gridPos": { "h": 10, "w": 9, "x": 7, "y": 41 },
     "yaxes": [
      { "format": "s", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds",
       "legendFormat": "Est. error(s)"
      },
      { "expr": "node_timex_offset_seconds", "legendFormat": "Offset: Node vs. Ref." },
      { "expr": "node_timex_maxerror_seconds", "legendFormat": "Max. Error (s)" }
     ]
    },
    {
     "title": "Rate of Transmitted Packets",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 41 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_packets_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__interval])",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__interval])\n",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received Packets",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 47 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__interval])\n",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received Packets Dropped",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 51 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__interval])",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets Dropped",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__interval])",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    },
    {
     "title": "Current KES Period",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 57 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "floor(avg(cardano_node_ChainDB_metrics_slotNum_int{namespace=~\"$namespace\", pod=~\"$pod\"})/3600)"
      }
     ]
    },
    {
     "title": "cardano-node/forks-created",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "cardano_node_ChainDB_metrics_forksCreatedNum_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs - leader only",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "TraceForgedBlock",
     "type": "logs",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceForgedBlock.*\""
      }
     ]
    },
    {
     "title": "TraceAdoptedBlock",
     "type": "logs",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceAdoptedBlock.*\""
      }
     ]
    },
    {
     "title": "TraceNodeIsLeader",
     "type": "logs",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceNodeIsLeader.*\""
      }
     ]
    },
    {
     "title": "TraceStartLeadershipCheck",
     "type": "logs",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceStartLeadershipCheck.*\""
      }
     ]
    },
    {
     "title": "TraceNodeNotLeader",
     "type": "logs",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceNodeNotLeader.*\""
      }
     ]
    },
    {
     "title": "OutcomeTraceForgeEvent",
     "type": "logs",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...OutcomeTraceForgeEvent.*\""
      }
     ]
    }
   ]
  },
  {
   "title": "Logs -  filter per kind",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "MeasureTxsTimeStop",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...MeasureTxsTimeStop.*\""
      }
     ]
    },
    {
     "title": "PeersFetch",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...PeersFetch.*\""
      }
     ]
    },
    {
     "title": "LogValue",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...LogValue.*\""
      }
     ]
    },
    {
     "title": "ErrorPolicyTrace",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...ErrorPolicyTrace.*\""
      }
     ]
    },
    {
     "title": "HandshakeTrace",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...HandshakeTrace.*\""
      }
     ]
    },
    {
     "title": "ChainSyncClientEvent.TraceDownloadedHeader",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...ChainSyncClientEvent.TraceDownloadedHeader.*\""
      }
     ]
    },
    {
     "title": "ChainSyncClientEvent.TraceFoundIntersection",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...ChainSyncClientEvent.TraceFoundIntersection.*\""
      }
     ]
    },
    {
     "title": "ChainSyncClientEvent.TraceException",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...ChainSyncClientEvent.TraceException.*\""
      }
     ]
    },
    {
     "title": "ChainSyncClientEvent.TraceRolledBack",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...ChainSyncClientEvent.TraceRolledBack.*\""
      }
     ]
    },
    {
     "title": "TraceAddBlockEvent.AddBlockValidation.ValidCandidate",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceAddBlockEvent.AddBlockValidation.ValidCandidate.*\""
      }
     ]
    },
    {
     "title": "TraceAddBlockEvent.TrySwitchToAFork",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceAddBlockEvent.TrySwitchToAFork.*\""
      }
     ]
    },
    {
     "title": "TraceAddBlockEvent.SwitchedToAFork",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceAddBlockEvent.SwitchedToAFork.*\""
      }
     ]
    },
    {
     "title": "TraceAddBlockEvent.AddedToCurrentChain",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 126 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceAddBlockEvent.AddedToCurrentChain.*\""
      }
     ]
    },
    {
     "title": "TraceLedgerEvent.TookSnapshot",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 133 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceLedgerEvent.TookSnapshot.*\""
      }
     ]
    },
    {
     "title": "TraceReaderEvent.NewReader",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 140 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceReaderEvent.NewReader.*\""
      }
     ]
    },
    {
     "title": "TraceReaderEvent.ReaderNoLongerInMem",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 147 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceReaderEvent.ReaderNoLongerInMem.*\""
      }
     ]
    },
    {
     "title": "TraceNoLedgerView",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 154 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceNoLedgerView.*\""
      }
     ]
    },
    {
     "title": "WithIPList SubscriptionTrace",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 161 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...WithIPList SubscriptionTrace.*\""
      }
     ]
    },
    {
     "title": "TraceOpenEvent.OpenedLgrDB",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 168 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceOpenEvent.OpenedLgrDB.*\""
      }
     ]
    },
    {
     "title": "TraceOpenEvent.OpenedDB",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 175 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"} |~ \".*kind...TraceOpenEvent.OpenedDB.*\""
      }
     ]
    }
   ]
  },
  {
   "title": "Logs - full stream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "cardano-node/logs for $pod in $namespace",
     "type": "logs",
     "description": "Shows every log collected by promtail",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "{namespace=~\"$namespace\", instance=~\"$pod\"}"
      }
     ]
    }
   ]
  }
 ]
}